name: 🚀 Deploy Private PHP Repo to Hostinger

on:
  push:
    branches:
      - main # change if your default branch is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.HOSTINGER_PAT }}

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.github*
            **/README.md
            **/LICENSE
